CREATE TABLE DA_SCOPE_DIRECTORY (
    id          VARCHAR2(36)   NOT NULL,
    scope_key   VARCHAR2(500)  NOT NULL,
    application VARCHAR2(255)  NOT NULL,
    snow_group  VARCHAR2(255),
    updated_by  VARCHAR2(255)  NOT NULL,
    updated_at  TIMESTAMP(6)   NOT NULL,
    CONSTRAINT PK_DA_SCOPE_DIRECTORY PRIMARY KEY (id)
);

CREATE INDEX IDX_DSD_APPLICATION
    ON DA_SCOPE_DIRECTORY (application);

CREATE INDEX IDX_DSD_APP_SNOW
    ON DA_SCOPE_DIRECTORY (application, snow_group);

CREATE UNIQUE INDEX UK_DSD_SCOPE_KEY
    ON DA_SCOPE_DIRECTORY (scope_key);
