ALTER TABLE SKILL_HUB_SKILL
    ADD content_source_type VARCHAR2(30) DEFAULT 'FILE_PATH' NOT NULL;

ALTER TABLE SKILL_HUB_SKILL
    ADD source_path VARCHAR2(500) DEFAULT 'README.md' NOT NULL;

ALTER TABLE SKILL_HUB_SKILL
    ADD content_sha256 VARCHAR2(64);

ALTER TABLE SKILL_HUB_SKILL
    ADD current_version_id VARCHAR2(36);

ALTER TABLE SKILL_HUB_SKILL
    ADD last_indexed_at TIMESTAMP;

CREATE TABLE SKILL_HUB_SKILL_VERSION (
    id VARCHAR2(36) PRIMARY KEY,
    skill_id VARCHAR2(36) NOT NULL,
    version_label VARCHAR2(40) NOT NULL,
    version_notes VARCHAR2(2000),
    source_path VARCHAR2(500) NOT NULL,
    content_snapshot CLOB NOT NULL,
    content_sha256 VARCHAR2(64) NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_SKILL_HUB_VERSION_SKILL
        FOREIGN KEY (skill_id) REFERENCES SKILL_HUB_SKILL (id)
);

CREATE INDEX IDX_SKILL_HUB_VERSION_SKILL_CREATED
    ON SKILL_HUB_SKILL_VERSION (skill_id, created_at);
