ALTER TABLE DA_AUDIT_LOG_ENTRY
    ADD (application VARCHAR2(255));

ALTER TABLE DA_AUDIT_LOG_ENTRY
    ADD (snow_group VARCHAR2(255));

ALTER TABLE DA_AUDIT_LOG_ENTRY
    ADD (agent VARCHAR2(255));

CREATE INDEX IDX_ALE_APPLICATION ON DA_AUDIT_LOG_ENTRY (application);
CREATE INDEX IDX_ALE_SNOW_GROUP ON DA_AUDIT_LOG_ENTRY (snow_group);
CREATE INDEX IDX_ALE_AGENT ON DA_AUDIT_LOG_ENTRY (agent);
