ALTER TABLE DA_AUDIT_LOG_ENTRY
    ADD COLUMN application VARCHAR(255);

ALTER TABLE DA_AUDIT_LOG_ENTRY
    ADD COLUMN snow_group VARCHAR(255);

ALTER TABLE DA_AUDIT_LOG_ENTRY
    ADD COLUMN agent VARCHAR(255);

CREATE INDEX IDX_ALE_APPLICATION ON DA_AUDIT_LOG_ENTRY (application);
CREATE INDEX IDX_ALE_SNOW_GROUP ON DA_AUDIT_LOG_ENTRY (snow_group);
CREATE INDEX IDX_ALE_AGENT ON DA_AUDIT_LOG_ENTRY (agent);
