package com.wwa.agenthub.contracts.enums;

/** Audit action types – append-only registry. */
public enum AuditActionType {
    upload,
    edit,
    view_result,
    approve,
    reject,
    rerun,
    skip,
    config_update,
    config_delete,
    auto_submit,
    request_start,
    request_fail,
    request_archive,
    request_restore,
    request_purge,
    access_grant_create,
    access_grant_update,
    access_grant_suspend,
    access_grant_reactivate,
    resource_center_update,
    resource_center_delete,
    integration_execution_start,
    integration_execution_progress,
    integration_artifact_register,
    integration_execution_submit,
    integration_execution_fail,
    integration_execution_cancel,
    integration_review_submit,
    integration_task_rerun,
    integration_task_binding_update,
    integration_input_artifact_approve
}
